package com.example.lotteryevent.viewmodels;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.ViewModel;

import com.example.lotteryevent.data.RegistrationHistoryItem;
import com.example.lotteryevent.repository.IRegistrationHistoryRepository;

import java.util.List;

/**
 * ViewModel responsible for exposing a user's registration history to the UI.
 * It retrieves history data and user-facing messages from an injected
 * {@link IRegistrationHistoryRepository}, keeping the UI layer lifecycle-aware
 * and decoupled from data retrieval logic.
 */
public class RegistrationHistoryViewModel extends ViewModel {
    private final IRegistrationHistoryRepository historyRepository;
    private final LiveData<List<RegistrationHistoryItem>> userHistory;

    /**
     * Creates a new ViewModel instance and initializes user history LiveData by
     * Stores a reference to the repository for message retrieval.
     * @param historyRepository the repository responsible for fetching
     *                          registration history data and emitting messages
     */
    public RegistrationHistoryViewModel(IRegistrationHistoryRepository historyRepository){
        this.historyRepository = historyRepository;
        this.userHistory = historyRepository.fetchRegistrationHistory();
    }

    /**
     * Gets users registered events.
     * @return a LiveData list containing the user's registration history.
     */
    public LiveData<List<RegistrationHistoryItem>> getUserHistory() {
        return userHistory;
    }

    /**
     * Provides a LiveData stream for user-facing messages generated by the
     * repository.
     * @return a LiveData object containing message strings for UI display
     */
    public LiveData<String> getUserMessage(){
        return historyRepository.getUserMessage();
    }
}